import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { AuthContextProvider } from "@/reusable/context/AuthContext";
import { getPlayer, getSession } from "@/reusable/lib/auth";
import { WsContextProvider } from "@/reusable/context/WsContext";
import { NotificationContextProvider } from "@/reusable/context/NotificationContext";
import { PlayerContextProvider } from "@/reusable/context/PlayerContext";

const raleway = localFont({
  src: "../public/fonts/Raleway-VariableFont_wght.ttf",
  variable: "--font-raleway",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const player = await getPlayer();

  return (
    <html className="h-full" lang="en">
      <body className={`${raleway.variable} flex h-full flex-col antialiased`}>
        <AuthContextProvider initialSession={JSON.stringify(session)}>
          <WsContextProvider>
            <NotificationContextProvider>
              <PlayerContextProvider playerData={JSON.stringify(player)}>
                {children}
              </PlayerContextProvider>
            </NotificationContextProvider>
          </WsContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
